/** Master genre list for the project form's Genre multi-select. Free text is
 *  still accepted (allowCustom) — this list only powers the searchable
 *  dropdown, it isn't an enum enforced at the DB level. */
export const GENRES: string[] = [
  "Comedy",
  "Drama",
  "Melodrama",
  "War",
  "Adventure",
  "Biography",
  "Crime",
  "Kids",
  "Documentary",
  "Romance",
  "Action",
  "Fantasy",
  "History",
  "Family",
  "Thriller",
  "Musical",
  "Short",
  "Detective",
  "Cartoon",
  "Horror",
  "Sitcom",
  "Psychological",
  "Animation",
  "Rock-Opera",
  "Tragicomedy",
  "Mystery",
  "Sci-Fi",
  "Teen Movies",
  "TV Show",
  "Stand-Up",
  "Theater",
  "Television play",
  "Opera",
  "Football Show",
  "Music",
  "Sport",
  "Psychological Thriller",
  "Reality Show",
  "Western",
  "Interview",
];
