export const GARM_CATEGORIES = [
  "Adult Content",
  "Arms & Ammunition",
  "Crime",
  "Drugs",
  "Hate Speech",
  "Military Conflict",
  "Profanity",
  "Sensitive Issues",
  "Spam",
  "Terrorism",
  "Tobacco",
] as const;

type SeedProject = {
  code: string;
  title: string;
  genre: string;
  synopsis: string;
  poster: string;
  gallery: string[];
  format: string;
  studio: string;
  status: "PRE_PRODUCTION" | "FILMING" | "POST_PRODUCTION" | "RELEASED";
  releaseLabel: string;
  countries: string;
  audienceGender: string;
  audienceAge: string;
  projViews: string;
  cpmRange: string;
  budgetRange: string;
  safetyScore: number;
  safety: "SAFE" | "REVIEW" | "RISK";
  catScores: number[]; // 11 scores aligned to GARM_CATEGORIES
  opps: {
    sceneNo: number;
    description: string;
    mood: string;
    rationale: string;
    type: string;
    prominence: string;
    category: string;
    estValue: number;
    durationSec: number;
    safety: number;
  }[];
  slotsTotal: number;
  slotsTaken: number;
  applicationDeadline: string; // ISO date
  releaseDate: string; // ISO date
  platforms: string[];
  placementType: "In-Frame" | "Story Integration" | "Mention";
  priceNote: string;
  actors: { name: string; role: string }[];
};

export type SeedPortfolio = {
  title: string;
  brand: string;
  description: string;
  image: string | null;
  metrics: Record<string, string>;
};

export type SeedPartner = {
  name: string;
  logo: string | null;
  url: string | null;
};

export const SEED_PROJECTS: SeedProject[] = [
  {
    code: "#PP-2026-8540",
    title: "Bandwidth",
    genre: "Coming-of-age",
    synopsis:
      "A small-town high-school senior with twelve million followers signs with a powerhouse LA talent agency and discovers a hidden file that turns every future decision into leverage.",
    poster: "/kino/proj-01-hero.jpg",
    gallery: [
      "/kino/frame-01.jpg",
      "/kino/frame-02.jpg",
      "/kino/frame-03.jpg",
      "/kino/frame-04.jpg",
      "/kino/frame-05.jpg",
    ],
    format: "50 ep × 1m 15s",
    studio: "Verita Vertical",
    status: "PRE_PRODUCTION",
    releaseLabel: "Q1 2027",
    countries: "US, UK, Australia, Canada, Mexico",
    audienceGender: "All",
    audienceAge: "16-30",
    projViews: "2.4M",
    cpmRange: "$3.60-$5.40",
    budgetRange: "$6,000,000 — $10,000,000",
    safetyScore: 80,
    safety: "SAFE",
    catScores: [88, 90, 70, 88, 92, 88, 81, 76, 96, 92, 88],
    opps: [
      {
        sceneNo: 1,
        description:
          "The protagonist navigates the chaotic high school cafeteria, recording a vlog while snacking.",
        mood: "youthful energy, authenticity",
        rationale: "Positions tech and jewelry at the forefront of Gen Z authenticity.",
        type: "visual",
        prominence: "background",
        category: "Beverages",
        estValue: 114,
        durationSec: 75,
        safety: 100,
      },
      {
        sceneNo: 1,
        description: "Signature necklace catches the light as she speaks to camera.",
        mood: "aspirational",
        rationale: "Jewelry as identity marker.",
        type: "visual",
        prominence: "active",
        category: "Jewelry",
        estValue: 114,
        durationSec: 75,
        safety: 100,
      },
      {
        sceneNo: 2,
        description: "She edits footage on a sleek laptop in her bedroom studio.",
        mood: "focused, creative",
        rationale: "Consumer tech in an authentic creator workflow.",
        type: "visual",
        prominence: "active",
        category: "Technology",
        estValue: 132,
        durationSec: 60,
        safety: 100,
      },
      {
        sceneNo: 3,
        description: "Morning routine — coffee and phone notifications pile up.",
        mood: "relatable",
        rationale: "Everyday beverage moment.",
        type: "visual",
        prominence: "background",
        category: "Home & Living",
        estValue: 98,
        durationSec: 45,
        safety: 95,
      },
    ],
    slotsTotal: 6,
    slotsTaken: 2,
    applicationDeadline: "2026-08-15",
    releaseDate: "2026-12-20",
    platforms: ["YouTube", "Kinodaran"],
    placementType: "In-Frame",
    priceNote: "Price on request",
    actors: [
      { name: "Mia Sinclair", role: "Lead — Teen Influencer" },
      { name: "Grant Okafor", role: "Talent Agent" },
      { name: "Priya Anand", role: "Best Friend / Rival Creator" },
    ],
  },
  {
    code: "#PP-2026-5657",
    title: "Code Bracelet",
    genre: "Medical Drama",
    synopsis:
      "After a sabbatical that ended a marriage and a research program, a pediatric oncologist returns to her floor to find her former patient — cured eleven years ago, now a resident — has come in with a fresh tumor and a secret request.",
    poster: "/kino/proj-02-hero.jpg",
    gallery: [
      "/kino/frame-06.jpg",
      "/kino/frame-07.jpg",
      "/kino/frame-08.jpg",
      "/kino/frame-09.jpg",
      "/kino/frame-10.jpg",
    ],
    format: "80 ep × 1m 30s",
    studio: "Helix Stories",
    status: "FILMING",
    releaseLabel: "Q3 2026",
    countries: "US, Canada, Germany, France",
    audienceGender: "All",
    audienceAge: "25-50",
    projViews: "1.8M",
    cpmRange: "$4.20-$6.10",
    budgetRange: "$11,000,000 — $16,000,000",
    safetyScore: 84,
    safety: "SAFE",
    catScores: [92, 94, 78, 74, 90, 86, 88, 68, 97, 94, 82],
    opps: [
      {
        sceneNo: 4,
        description: "The resident checks vitals on a hospital-grade wearable monitor at the nurses' station.",
        mood: "clinical precision",
        rationale: "Medical tech branding reinforces trust and authenticity of the setting.",
        type: "visual",
        prominence: "background",
        category: "Technology",
        estValue: 145,
        durationSec: 50,
        safety: 100,
      },
      {
        sceneNo: 6,
        description: "Late-night coffee run in the hospital break room between shifts.",
        mood: "exhausted camaraderie",
        rationale: "Beverage placement in a relatable break-room ritual.",
        type: "visual",
        prominence: "background",
        category: "Beverages",
        estValue: 88,
        durationSec: 40,
        safety: 100,
      },
      {
        sceneNo: 9,
        description: "She drives home in the rain, dashboard lights glowing, talking to her daughter on speakerphone.",
        mood: "quiet vulnerability",
        rationale: "Automotive interior showcased in an emotionally resonant scene.",
        type: "visual",
        prominence: "active",
        category: "Automotive",
        estValue: 210,
        durationSec: 65,
        safety: 95,
      },
      {
        sceneNo: 12,
        description: "A pharmaceutical rep leaves a branded tote bag of samples on the reception desk.",
        mood: "procedural realism",
        rationale: "Healthcare-adjacent brand visibility in a natural workplace moment.",
        type: "visual",
        prominence: "background",
        category: "Healthcare",
        estValue: 96,
        durationSec: 30,
        safety: 90,
      },
    ],
    slotsTotal: 8,
    slotsTaken: 5,
    applicationDeadline: "2026-07-30",
    releaseDate: "2026-09-15",
    platforms: ["Kinodaran", "TV"],
    placementType: "Story Integration",
    priceNote: "Price on request",
    actors: [
      { name: "Dr. Elena Foster", role: "Lead — Pediatric Oncologist" },
      { name: "Caleb Whitmore", role: "Resident / Former Patient" },
      { name: "Dr. Robert Nash", role: "Chief of Medicine" },
    ],
  },
  {
    code: "#PP-2026-2384",
    title: "Cold Case Files Active",
    genre: "Crime Procedural",
    synopsis:
      "A behavioral profiler is pulled into a homicide that mirrors the unsolved murder of her own father twenty-five years ago. Closing the case will cost her every certainty about who in her family told the truth that summer.",
    poster: "/kino/proj-03-hero.jpg",
    gallery: [
      "/kino/frame-11.jpg",
      "/kino/frame-12.jpg",
      "/kino/frame-13.jpg",
      "/kino/frame-14.jpg",
      "/kino/frame-15.jpg",
    ],
    format: "100 ep × 1m 40s",
    studio: "Echo Microdrama",
    status: "POST_PRODUCTION",
    releaseLabel: "Q4 2026",
    countries: "US, UK, Canada",
    audienceGender: "All",
    audienceAge: "25-55",
    projViews: "2.3M",
    cpmRange: "$3.90-$5.80",
    budgetRange: "$12,000,000 — $18,000,000",
    safetyScore: 66,
    safety: "REVIEW",
    catScores: [72, 58, 40, 62, 70, 55, 60, 48, 90, 58, 74],
    opps: [
      {
        sceneNo: 2,
        description: "The profiler reviews case files spread across a laptop and tablet in her home office.",
        mood: "tense focus",
        rationale: "Consumer tech placement in a high-stakes investigative moment.",
        type: "visual",
        prominence: "background",
        category: "Technology",
        estValue: 120,
        durationSec: 55,
        safety: 80,
      },
      {
        sceneNo: 5,
        description: "A tense stakeout in an unmarked SUV outside a suspect's house at dawn.",
        mood: "gritty suspense",
        rationale: "Automotive brand visible during a signature procedural sequence.",
        type: "visual",
        prominence: "active",
        category: "Automotive",
        estValue: 175,
        durationSec: 70,
        safety: 70,
      },
      {
        sceneNo: 8,
        description: "She grabs a quick energy drink before a late-night interrogation.",
        mood: "adrenaline",
        rationale: "Beverage placement tied to procedural urgency.",
        type: "visual",
        prominence: "background",
        category: "Beverages",
        estValue: 92,
        durationSec: 35,
        safety: 85,
      },
      {
        sceneNo: 11,
        description: "The precinct bullpen scene features branded desk phones and radios in the background.",
        mood: "procedural realism",
        rationale: "Office/telecom brand visibility in an ensemble scene.",
        type: "visual",
        prominence: "background",
        category: "Technology",
        estValue: 78,
        durationSec: 40,
        safety: 88,
      },
    ],
    slotsTotal: 5,
    slotsTaken: 3,
    applicationDeadline: "2026-08-20",
    releaseDate: "2026-11-10",
    platforms: ["Kinodaran", "TV", "YouTube"],
    placementType: "In-Frame",
    priceNote: "Price on request",
    actors: [
      { name: "Dana Kowalski", role: "Lead — Behavioral Profiler" },
      { name: "Marcus Reyes", role: "Detective Partner" },
      { name: "Tom Kowalski", role: "Her Estranged Brother" },
    ],
  },
  {
    code: "#PP-2026-9012",
    title: "The Longest Night",
    genre: "Sci-Fi Thriller",
    synopsis:
      "When a deep-space maintenance crew wakes from cryo two hundred years early, they must decide whether the AI that saved them is protecting the mission — or replacing it.",
    poster: "/kino/proj-04-hero.jpg",
    gallery: [
      "/kino/frame-16.jpg",
      "/kino/frame-17.jpg",
      "/kino/frame-18.jpg",
      "/kino/frame-19.jpg",
      "/kino/frame-20.jpg",
    ],
    format: "40 ep × 2m 00s",
    studio: "Nova Frame",
    status: "PRE_PRODUCTION",
    releaseLabel: "Q2 2027",
    countries: "US, UK, Germany, Japan, South Korea",
    audienceGender: "All",
    audienceAge: "18-40",
    projViews: "3.1M",
    cpmRange: "$4.80-$7.20",
    budgetRange: "$20,000,000 — $28,000,000",
    safetyScore: 82,
    safety: "SAFE",
    catScores: [90, 68, 76, 84, 88, 60, 82, 72, 95, 66, 90],
    opps: [
      {
        sceneNo: 1,
        description: "Crew members wake from cryo pods, disoriented, surrounded by sleek console displays.",
        mood: "eerie wonder",
        rationale: "Futuristic tech branding embedded in near-future set design.",
        type: "visual",
        prominence: "background",
        category: "Technology",
        estValue: 260,
        durationSec: 90,
        safety: 95,
      },
      {
        sceneNo: 3,
        description: "The engineer repairs a life-support unit using a branded multitool kit.",
        mood: "resourceful tension",
        rationale: "Tool/hardware brand visibility tied to a competence moment.",
        type: "visual",
        prominence: "active",
        category: "Tools & Hardware",
        estValue: 150,
        durationSec: 50,
        safety: 98,
      },
      {
        sceneNo: 7,
        description: "Crew shares a rehydrated meal pack in the mess hall, discussing the AI's motives.",
        mood: "uneasy camaraderie",
        rationale: "Food & beverage brand woven into world-building dialogue scene.",
        type: "visual",
        prominence: "background",
        category: "Food & Beverages",
        estValue: 110,
        durationSec: 60,
        safety: 96,
      },
      {
        sceneNo: 10,
        description: "A distress beacon broadcasts through branded communications hardware on the bridge.",
        mood: "high stakes",
        rationale: "Telecom/comms brand visibility in the climactic sequence.",
        type: "audio",
        prominence: "active",
        category: "Technology",
        estValue: 190,
        durationSec: 45,
        safety: 92,
      },
    ],
    slotsTotal: 7,
    slotsTaken: 1,
    applicationDeadline: "2026-09-25",
    releaseDate: "2026-12-28",
    platforms: ["YouTube", "Kinodaran"],
    placementType: "Story Integration",
    priceNote: "Price on request",
    actors: [
      { name: "Captain Ilsa Voss", role: "Mission Commander" },
      { name: "Theo Marsh", role: "Systems Engineer" },
      { name: "ARIA", role: "Ship AI (voice)" },
    ],
  },
  {
    code: "#PP-2026-3345",
    title: "Saffron Road",
    genre: "Romance",
    synopsis:
      "A food-truck chef and a Michelin critic keep colliding across one unforgettable summer of markets, feuds and second chances in a coastal town that never forgets a recipe.",
    poster: "/kino/proj-05-hero.jpg",
    gallery: [
      "/kino/frame-21.jpg",
      "/kino/frame-22.jpg",
      "/kino/frame-23.jpg",
      "/kino/frame-24.jpg",
      "/kino/frame-25.jpg",
    ],
    format: "60 ep × 1m 20s",
    studio: "Amber Lane",
    status: "RELEASED",
    releaseLabel: "Streaming now",
    countries: "US, UK, Italy, Spain, Australia",
    audienceGender: "Female",
    audienceAge: "20-45",
    projViews: "1.5M",
    cpmRange: "$3.20-$4.90",
    budgetRange: "$4,000,000 — $7,000,000",
    safetyScore: 91,
    safety: "SAFE",
    catScores: [95, 98, 92, 90, 96, 97, 88, 84, 98, 99, 92],
    opps: [
      {
        sceneNo: 2,
        description: "The chef preps fresh produce at a sun-drenched farmers market stall.",
        mood: "warm, sensory",
        rationale: "Food & grocery brand visibility in an aspirational lifestyle setting.",
        type: "visual",
        prominence: "active",
        category: "Food & Beverages",
        estValue: 105,
        durationSec: 55,
        safety: 100,
      },
      {
        sceneNo: 4,
        description: "The critic sips coffee alone at a seaside café, scribbling notes.",
        mood: "contemplative",
        rationale: "Beverage brand placement in an intimate character beat.",
        type: "visual",
        prominence: "background",
        category: "Beverages",
        estValue: 82,
        durationSec: 40,
        safety: 100,
      },
      {
        sceneNo: 6,
        description: "A golden-hour bike ride along the coastal road, market bags swinging from the handlebars.",
        mood: "romantic, breezy",
        rationale: "Lifestyle/apparel brand visibility during a signature romantic sequence.",
        type: "visual",
        prominence: "background",
        category: "Apparel",
        estValue: 96,
        durationSec: 50,
        safety: 100,
      },
      {
        sceneNo: 9,
        description: "The food truck's new espresso machine gets its debut during the town festival finale.",
        mood: "triumphant, joyful",
        rationale: "Home & kitchen appliance brand featured at the emotional climax.",
        type: "visual",
        prominence: "active",
        category: "Home & Living",
        estValue: 128,
        durationSec: 60,
        safety: 100,
      },
    ],
    slotsTotal: 4,
    slotsTaken: 4,
    applicationDeadline: "2026-07-25",
    releaseDate: "2026-08-01",
    platforms: ["Kinodaran", "YouTube"],
    placementType: "Mention",
    priceNote: "Price on request",
    actors: [
      { name: "Sofia Marchetti", role: "Lead — Food-Truck Chef" },
      { name: "James Calloway", role: "Michelin Critic" },
      { name: "Noor Haddad", role: "Sous Chef / Best Friend" },
    ],
  },
  {
    code: "#PP-2026-7788",
    title: "Ironwood County",
    genre: "Western Drama",
    synopsis:
      "Three generations of a ranching family fight a mining conglomerate, a drought and each other over the last unfenced valley in the state.",
    poster: "/kino/proj-06-hero.jpg",
    gallery: [
      "/kino/frame-26.jpg",
      "/kino/frame-27.jpg",
      "/kino/frame-28.jpg",
      "/kino/frame-29.jpg",
      "/kino/frame-30.jpg",
    ],
    format: "70 ep × 1m 45s",
    studio: "Ridgeline",
    status: "FILMING",
    releaseLabel: "Q1 2027",
    countries: "US, Canada, Australia",
    audienceGender: "All",
    audienceAge: "30-60",
    projViews: "2.0M",
    cpmRange: "$3.50-$5.10",
    budgetRange: "$9,000,000 — $14,000,000",
    safetyScore: 73,
    safety: "REVIEW",
    catScores: [82, 55, 64, 70, 68, 50, 58, 62, 92, 60, 65],
    opps: [
      {
        sceneNo: 3,
        description: "The eldest son repairs a pickup truck engine in the barn at sunrise.",
        mood: "rugged, dependable",
        rationale: "Automotive brand visibility rooted in working-ranch authenticity.",
        type: "visual",
        prominence: "active",
        category: "Automotive",
        estValue: 165,
        durationSec: 65,
        safety: 85,
      },
      {
        sceneNo: 5,
        description: "The family gathers around branded work boots and denim drying by the fireplace.",
        mood: "grounded, generational",
        rationale: "Workwear apparel brand tied to family heritage theme.",
        type: "visual",
        prominence: "background",
        category: "Apparel",
        estValue: 102,
        durationSec: 45,
        safety: 90,
      },
      {
        sceneNo: 8,
        description: "A tense negotiation with the mining executive over branded coffee in the ranch kitchen.",
        mood: "simmering conflict",
        rationale: "Beverage brand present during a key dramatic confrontation.",
        type: "visual",
        prominence: "background",
        category: "Beverages",
        estValue: 88,
        durationSec: 50,
        safety: 80,
      },
      {
        sceneNo: 11,
        description: "The youngest daughter livestreams the drought-stricken valley on her phone for a news outlet.",
        mood: "urgent, modern",
        rationale: "Consumer tech placement bridging old and new generations.",
        type: "visual",
        prominence: "active",
        category: "Technology",
        estValue: 118,
        durationSec: 40,
        safety: 88,
      },
    ],
    slotsTotal: 6,
    slotsTaken: 2,
    applicationDeadline: "2026-09-10",
    releaseDate: "2026-12-15",
    platforms: ["Kinodaran", "TV"],
    placementType: "In-Frame",
    priceNote: "Price on request",
    actors: [
      { name: "Wade Calder", role: "Eldest Son" },
      { name: "Ruth Calder", role: "Family Matriarch" },
      { name: "Josie Calder", role: "Youngest Daughter" },
    ],
  },
];

export const SEED_PORTFOLIO: SeedPortfolio[] = [
  {
    title: "Streaming Sneakers on the Fast Track",
    brand: "Voltrun Athletics",
    description:
      "A hero sneaker drop was woven into three chase sequences of a top-10 microdrama, with the product visible in every close-up of the lead's morning run ritual.",
    image: "/kino/frame-01.jpg",
    metrics: { views: "2.1M", recall: "+38%", ctr: "4.2%" },
  },
  {
    title: "Coffee Brand Becomes a Character Beat",
    brand: "Ember Roasters",
    description:
      "A recurring café scene turned a mid-size coffee brand into a running visual motif across an entire medical-drama season, driving a measurable lift in local store visits.",
    image: "/kino/frame-06.jpg",
    metrics: { views: "1.6M", recall: "+29%", storeVisits: "+14%" },
  },
  {
    title: "SUV Hero Shot in a Procedural Finale",
    brand: "Ridgemont Motors",
    description:
      "A dawn stakeout sequence placed the client's flagship SUV at the center of a crime procedural's most-shared clip, generating outsized organic reach.",
    image: "/kino/frame-12.jpg",
    metrics: { views: "3.4M", recall: "+41%", shares: "58K" },
  },
  {
    title: "Consumer Tech in a Sci-Fi World-Build",
    brand: "Halcyon Devices",
    description:
      "Near-future console displays and comms hardware were designed around the client's real product line, embedding the brand into the show's futuristic identity.",
    image: "/kino/frame-17.jpg",
    metrics: { views: "2.8M", recall: "+33%", sentiment: "92% positive" },
  },
  {
    title: "Espresso Machine Steals the Finale",
    brand: "Marchetti Home",
    description:
      "A single appliance reveal at the emotional climax of a romance series became the most-replayed moment of the season, boosting brand search volume overnight.",
    image: "/kino/frame-24.jpg",
    metrics: { views: "1.9M", recall: "+35%", searchLift: "+62%" },
  },
  {
    title: "Workwear Woven Into Family Legacy",
    brand: "Ironclad Workwear",
    description:
      "Three generations of a ranching family wore the client's boots and denim across a full season, tying the brand to themes of heritage and durability.",
    image: "/kino/frame-27.jpg",
    metrics: { views: "1.3M", recall: "+27%", recallDurability: "+45%" },
  },
];

export const SEED_PARTNERS: SeedPartner[] = [
  { name: "Verita Vertical", logo: null, url: null },
  { name: "Helix Stories", logo: null, url: null },
  { name: "Echo Microdrama", logo: null, url: null },
  { name: "Nova Frame", logo: null, url: null },
  { name: "Amber Lane", logo: null, url: null },
  { name: "Ridgeline", logo: null, url: null },
  { name: "Kinodaran Studios", logo: null, url: null },
  { name: "Prism Vertical Network", logo: null, url: null },
];
